# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Language.create([
  {name: "Afrikaans", code: "af"},
  {name: "አማርኛ", code: "am"},
  {name: "العربية", code: "ar"},
  {name: "Azərbaycan dili", code: "az"},
  {name: "Беларуская", code: "be"},
  {name: "български", code: "bg"},
  {name: "বাংলা", code: "bn"},
  {name: "bosanski", code: "bs"},
  {name: "català", code: "ca"},
  {name: "Cebuano", code: "ceb"},
  {name: "Corse", code: "co"},
  {name: "čeština", code: "cs"},
  {name: "Cymraeg", code: "cy"},
  {name: "Dansk", code: "da"},
  {name: "Deutsch", code: "de"},
  {name: "Ελληνικά", code: "el"},
  {name: "English", code: "en"},
  {name: "Esperanto", code: "eo"},
  {name: "español", code: "es"},
  {name: "eesti", code: "et"},
  {name: "euskara", code: "eu"},
  {name: "فارسی", code: "fa"},
  {name: "suomi", code: "fi"},
  {name: "Français", code: "fr"},
  {name: "Frysk", code: "fy"},
  {name: "Gaeilge", code: "ga"},
  {name: "Gàidhlig", code: "gd"},
  {name: "galego", code: "gl"},
  {name: "ગુજરાતી", code: "gu"},
  {name: "Hausa", code: "ha"},
  {name: "Hawaiian", code: "haw"},
  {name: "עברית", code: "he"},
  {name: "हिन्दी", code: "hi"},
  {name: "Hmong", code: "hmn"},
  {name: "hrvatski", code: "hr"},
  {name: "Kreyòl Ayisyen", code: "ht"},
  {name: "magyar", code: "hu"},
  {name: "հայերեն", code: "hy"},
  {name: "Indonesia", code: "id"},
  {name: "Igbo", code: "ig"},
  {name: "íslenska", code: "is"},
  {name: "Italiano", code: "it"},
  {name: "עברית", code: "iw"},
  {name: "日本語", code: "ja"},
  {name: "Javanese", code: "jw"},
  {name: "ქართული", code: "ka"},
  {name: "қазақ", code: "kk"},
  {name: "ខ្មែរ", code: "km"},
  {name: "ಕನ್ನಡ", code: "kn"},
  {name: "한국어", code: "ko"},
  {name: "Kurdish (Kurmanji)", code: "ku"},
  {name: "кыргызча", code: "ky"},
  {name: "Latin", code: "la"},
  {name: "Luxembourgish", code: "lb"},
  {name: "ລາວ", code: "lo"},
  {name: "lietuvių", code: "lt"},
  {name: "latviešu", code: "lv"},
  {name: "Malagasy", code: "mg"},
  {name: "Māori", code: "mi"},
  {name: "македонски", code: "mk"},
  {name: "മലയാളം", code: "ml"},
  {name: "Монгол", code: "mn"},
  {name: "मराठी", code: "mr"},
  {name: "Melayu", code: "ms"},
  {name: "Malti", code: "mt"},
  {name: "မြန်မာ (မြန်မာ)", code: "my"},
  {name: "नेपाली", code: "ne"},
  {name: "Nederlands", code: "nl"},
  {name: "norsk", code: "no"},
  {name: "Chichewa", code: "ny"},
  {name: "Odia (Oriya)", code: "or"},
  {name: "ਪੰਜਾਬੀ", code: "pa"},
  {name: "polski", code: "pl"},
  {name: "پښتو", code: "ps"},
  {name: "Portuguese", code: "pt"},
  {name: "Română", code: "ro"},
  {name: "русский", code: "ru"},
  {name: "Kinyarwanda", code: "rw"},
  {name: "سنڌي", code: "sd"},
  {name: "සිංහල", code: "si"},
  {name: "slovenčina", code: "sk"},
  {name: "slovenščina", code: "sl"},
  {name: "Samoan", code: "sm"},
  {name: "ChiShona", code: "sn"},
  {name: "Soomaali", code: "so"},
  {name: "Shqip", code: "sq"},
  {name: "српски", code: "sr"},
  {name: "Sesotho", code: "st"},
  {name: "Basa Sunda", code: "su"},
  {name: "svenska", code: "sv"},
  {name: "Kiswahili", code: "sw"},
  {name: "தமிழ்", code: "ta"},
  {name: "తెలుగు", code: "te"},
  {name: "Тоҷикӣ", code: "tg"},
  {name: "ไทย", code: "th"},
  {name: "Turkmen", code: "tk"},
  {name: "Filipino", code: "tl"},
  {name: "Türkçe", code: "tr"},
  {name: "Tatar", code: "tt"},
  {name: "Uyghur", code: "ug"},
  {name: "українська", code: "uk"},
  {name: "اردو", code: "ur"},
  {name: "O‘zbek", code: "uz"},
  {name: "Việt", code: "vi"},
  {name: "IsiXhosa", code: "xh"},
  {name: "יידיש", code: "yi"},
  {name: "Èdè Yorùbá", code: "yo"},
  {name: "中文(简体)", code: "zh"},
  {name: "中文(简体)", code: "zh-CN"},
  {name: "中文 (繁體)", code: "zh-TW"},
  {name: "isiZulu", code: "zu"}
])
