Language.create([
  { name: "Afrikaans", code: "af", name_in_english: "Afrikaans" },
  { name: "አማርኛ", code: "am", name_in_english: "Amharic" },
  { name: "العربية", code: "ar", name_in_english: "Arabic" },
  { name: "Azərbaycan dili", code: "az", name_in_english: "Azerbaijani" },
  { name: "Беларуская", code: "be", name_in_english: "Belarusian" },
  { name: "български", code: "bg", name_in_english: "Bulgarian" },
  { name: "বাংলা", code: "bn", name_in_english: "Bengali" },
  { name: "bosanski", code: "bs", name_in_english: "Bosnian" },
  { name: "català", code: "ca", name_in_english: "Catalan" },
  { name: "Cebuano", code: "ceb", name_in_english: "Cebuano" },
  { name: "Corse", code: "co", name_in_english: "Corsican" },
  { name: "čeština", code: "cs", name_in_english: "Czech" },
  { name: "Cymraeg", code: "cy", name_in_english: "Welsh" },
  { name: "Dansk", code: "da", name_in_english: "Danish" },
  { name: "Deutsch", code: "de", name_in_english: "German" },
  { name: "Ελληνικά", code: "el", name_in_english: "Greek" },
  { name: "English", code: "en", name_in_english: "English" },
  { name: "Esperanto", code: "eo", name_in_english: "Esperanto" },
  { name: "español", code: "es", name_in_english: "Spanish" },
  { name: "eesti", code: "et", name_in_english: "Estonian" },
  { name: "euskara", code: "eu", name_in_english: "Basque" },
  { name: "فارسی", code: "fa", name_in_english: "Persian" },
  { name: "suomi", code: "fi", name_in_english: "Finnish" },
  { name: "Français", code: "fr", name_in_english: "French" },
  { name: "Frysk", code: "fy", name_in_english: "Frisian" },
  { name: "Gaeilge", code: "ga", name_in_english: "Irish" },
  { name: "Gàidhlig", code: "gd", name_in_english: "Scots Gaelic" },
  { name: "galego", code: "gl", name_in_english: "Galician" },
  { name: "ગુજરાતી", code: "gu", name_in_english: "Gujarati" },
  { name: "Hausa", code: "ha", name_in_english: "Hausa" },
  { name: "Hawaiian", code: "haw", name_in_english: "Hawaiian" },
  { name: "עברית", code: "he", name_in_english: "Hebrew" },
  { name: "हिन्दी", code: "hi", name_in_english: "Hindi" },
  { name: "Hmong", code: "hmn", name_in_english: "Hmong" },
  { name: "hrvatski", code: "hr", name_in_english: "Croatian" },
  { name: "Kreyòl Ayisyen", code: "ht", name_in_english: "Haitian Creole" },
  { name: "magyar", code: "hu", name_in_english: "Hungarian" },
  { name: "հայերեն", code: "hy", name_in_english: "Armenian" },
  { name: "Indonesia", code: "id", name_in_english: "Indonesian" },
  { name: "Igbo", code: "ig", name_in_english: "Igbo" },
  { name: "íslenska", code: "is", name_in_english: "Icelandic" },
  { name: "Italiano", code: "it", name_in_english: "Italian" },
  { name: "עברית", code: "iw", name_in_english: "Hebrew" },
  { name: "日本語", code: "ja", name_in_english: "Japanese" },
  { name: "Javanese", code: "jw", name_in_english: "Javanese" },
  { name: "ქართული", code: "ka", name_in_english: "Georgian" },
  { name: "қазақ", code: "kk", name_in_english: "Kazakh" },
  { name: "ខ្មែរ", code: "km", name_in_english: "Khmer" },
  { name: "ಕನ್ನಡ", code: "kn", name_in_english: "Kannada" },
  { name: "한국어", code: "ko", name_in_english: "Korean" },
  { name: "Kurdish (Kurmanji)", code: "ku", name_in_english: "Kurdish (Kurmanji)" },
  { name: "кыргызча", code: "ky", name_in_english: "Kyrgyz" },
  { name: "Latin", code: "la", name_in_english: "Latin" },
  { name: "Luxembourgish", code: "lb", name_in_english: "Luxembourgish" },
  { name: "ລາວ", code: "lo", name_in_english: "Lao" },
  { name: "lietuvių", code: "lt", name_in_english: "Lithuanian" },
  { name: "latviešu", code: "lv", name_in_english: "Latvian" },
  { name: "Malagasy", code: "mg", name_in_english: "Malagasy" },
  { name: "Māori", code: "mi", name_in_english: "Maori" },
  { name: "македонски", code: "mk", name_in_english: "Macedonian" },
  { name: "മലയാളം", code: "ml", name_in_english: "Malayalam" },
  { name: "Монгол", code: "mn", name_in_english: "Mongolian" },
  { name: "मराठी", code: "mr", name_in_english: "Marathi" },
  { name: "Melayu", code: "ms", name_in_english: "Malay" },
  { name: "Malti", code: "mt", name_in_english: "Maltese" },
  { name: "မြန်မာ (မြန်မာ)", code: "my", name_in_english: "Myanmar (Burmese)" },
  { name: "नेपाली", code: "ne", name_in_english: "Nepali" },
  { name: "Nederlands", code: "nl", name_in_english: "Dutch" },
  { name: "norsk", code: "no", name_in_english: "Norwegian" },
  { name: "Chichewa", code: "ny", name_in_english: "Chichewa" },
  { name: "Odia (Oriya)", code: "or", name_in_english: "Odia (Oriya)" },
  { name: "ਪੰਜਾਬੀ", code: "pa", name_in_english: "Punjabi" },
  { name: "polski", code: "pl", name_in_english: "Polish" },
  { name: "پښتو", code: "ps", name_in_english: "Pashto" },
  { name: "Portuguese", code: "pt", name_in_english: "Portuguese" },
  { name: "Română", code: "ro", name_in_english: "Romanian" },
  { name: "русский", code: "ru", name_in_english: "Russian" },
  { name: "Kinyarwanda", code: "rw", name_in_english: "Kinyarwanda" },
  { name: "سنڌي", code: "sd", name_in_english: "Sindhi" },
  { name: "සිංහල", code: "si", name_in_english: "Sinhala" },
  { name: "slovenčina", code: "sk", name_in_english: "Slovak" },
  { name: "slovenščina", code: "sl", name_in_english: "Slovenian" },
  { name: "Samoan", code: "sm", name_in_english: "Samoan" },
  { name: "ChiShona", code: "sn", name_in_english: "Shona" },
  { name: "Soomaali", code: "so", name_in_english: "Somali" },
  { name: "Shqip", code: "sq", name_in_english: "Albanian" },
  { name: "српски", code: "sr", name_in_english: "Serbian" },
  { name: "Sesotho", code: "st", name_in_english: "Sesotho" },
  { name: "Basa Sunda", code: "su", name_in_english: "Sundanese" },
  { name: "svenska", code: "sv", name_in_english: "Swedish" },
  { name: "Kiswahili", code: "sw", name_in_english: "Swahili" },
  { name: "தமிழ்", code: "ta", name_in_english: "Tamil" },
  { name: "తెలుగు", code: "te", name_in_english: "Telugu" },
  { name: "Тоҷикӣ", code: "tg", name_in_english: "Tajik" },
  { name: "ไทย", code: "th", name_in_english: "Thai" },
  { name: "Turkmen", code: "tk", name_in_english: "Turkmen" },
  { name: "Filipino", code: "tl", name_in_english: "Filipino" },
  { name: "Türkçe", code: "tr", name_in_english: "Turkish" },
  { name: "Tatar", code: "tt", name_in_english: "Tatar" },
  { name: "Uyghur", code: "ug", name_in_english: "Uyghur" },
  { name: "українська", code: "uk", name_in_english: "Ukrainian" },
  { name: "اردو", code: "ur", name_in_english: "Urdu" },
  { name: "O‘zbek", code: "uz", name_in_english: "Uzbek" },
  { name: "Việt", code: "vi", name_in_english: "Vietnamese" },
  { name: "IsiXhosa", code: "xh", name_in_english: "Xhosa" },
  { name: "יידיש", code: "yi", name_in_english: "Yiddish" },
  { name: "Èdè Yorùbá", code: "yo", name_in_english: "Yoruba" },
  { name: "中文(简体)", code: "zh", name_in_english: "Chinese (Simplified)" },
  { name: "中文(简体)", code: "zh-CN", name_in_english: "Chinese (Simplified)" },
  { name: "中文 (繁體)", code: "zh-TW", name_in_english: "Chinese (Traditional)" },
  { name: "isiZulu", code: "zu", name_in_english: "Zulu" },
])
